steps:
- name: 'us.gcr.io/t-system-422014-h3/ticketing-client'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'us.gcr.io/t-system-422014-h3/ticketing-client'
  - '.'

- name: 'us.gcr.io/t-system-422014-h3/ticketing-client'
  id: Push
  args:
  - 'push'
  - 'us.gcr.io/t-system-422014-h3/ticketing-client'

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=infra/k8s/client-depl.yaml
  - --image=us.gcr.io/t-system-422014-h3/ticketing-client
  - --location=${_CLOUDSDK_COMPUTE_ZONE}
  - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}

options:
  logging: CLOUD_LOGGING_ONLY