#Build the image
steps:
- name: "gcr.io/cloud-builders/docker"
  args:
  - build
  - "--tag=us.gcr.io/t-system-422014-h3/ticketing-client"
  - "--file=/client/Dockerfile"
  - .

#Push the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/t-system-422014-h3/ticketing-client']

# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=infra/k8s/client-depl.yaml
  - --image=us.gcr.io/t-system-422014-h3/ticketing-client
  - --location=us-central1-c
  - --cluster=app-cluster

options:
  logging: CLOUD_LOGGING_ONLY