steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'us.gcr.io/t-system-422014-h3/ticketing-client:${COMMIT_SHA}', '-f', 'client/Dockerfile']


# Push the container image


- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/t-system-422014-h3/ticketing-client:${COMMIT_SHA}']
# Create release in Google Cloud Deploy


- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "gitops",
      "--region", "asia-east1",
      "--images", "image=us.gcr.io/t-system-422014-h3/ticketing-client:${COMMIT_SHA}"
    ]

options:
  logging: CLOUD_LOGGING_ONLY
