apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-tickets
spec:
  storageClassName: premium-rwo
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
