name: Deploy Client

on:
  push:
    branches:
    - 'master'
  paths:
    - 'client/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GKE_PROJECT }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/client
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/client

    - name: deploy to gke
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud container clusters get-credentials app-cluster --region us-central1-c
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" infra/k8s/client-depl.yaml
        kubectl apply -f infra/k8s/client-depl.yaml